package state

var ValidCoords = map[Coord]bool{
	Coord{Rank1, FileA}: true,
	Coord{Rank2, FileA}: true,
	Coord{Rank3, FileA}: true,
	Coord{Rank4, FileA}: true,
	Coord{Rank5, FileA}: true,
	Coord{Rank6, FileA}: true,
	Coord{Rank7, FileA}: true,
	Coord{Rank8, FileA}: true,

	Coord{Rank1, FileB}: true,
	Coord{Rank2, FileB}: true,
	Coord{Rank3, FileB}: true,
	Coord{Rank4, FileB}: true,
	Coord{Rank5, FileB}: true,
	Coord{Rank6, FileB}: true,
	Coord{Rank7, FileB}: true,
	Coord{Rank8, FileB}: true,

	Coord{Rank1, FileC}: true,
	Coord{Rank2, FileC}: true,
	Coord{Rank3, FileC}: true,
	Coord{Rank4, FileC}: true,
	Coord{Rank5, FileC}: true,
	Coord{Rank6, FileC}: true,
	Coord{Rank7, FileC}: true,
	Coord{Rank8, FileC}: true,

	Coord{Rank1, FileD}: true,
	Coord{Rank2, FileD}: true,
	Coord{Rank3, FileD}: true,
	Coord{Rank4, FileD}: true,
	Coord{Rank5, FileD}: true,
	Coord{Rank6, FileD}: true,
	Coord{Rank7, FileD}: true,
	Coord{Rank8, FileD}: true,

	Coord{Rank1, FileE}: true,
	Coord{Rank2, FileE}: true,
	Coord{Rank3, FileE}: true,
	Coord{Rank4, FileE}: true,
	Coord{Rank5, FileE}: true,
	Coord{Rank6, FileE}: true,
	Coord{Rank7, FileE}: true,
	Coord{Rank8, FileE}: true,

	Coord{Rank1, FileF}: true,
	Coord{Rank2, FileF}: true,
	Coord{Rank3, FileF}: true,
	Coord{Rank4, FileF}: true,
	Coord{Rank5, FileF}: true,
	Coord{Rank6, FileF}: true,
	Coord{Rank7, FileF}: true,
	Coord{Rank8, FileF}: true,

	Coord{Rank1, FileG}: true,
	Coord{Rank2, FileG}: true,
	Coord{Rank3, FileG}: true,
	Coord{Rank4, FileG}: true,
	Coord{Rank5, FileG}: true,
	Coord{Rank6, FileG}: true,
	Coord{Rank7, FileG}: true,
	Coord{Rank8, FileG}: true,

	Coord{Rank1, FileH}: true,
	Coord{Rank2, FileH}: true,
	Coord{Rank3, FileH}: true,
	Coord{Rank4, FileH}: true,
	Coord{Rank5, FileH}: true,
	Coord{Rank6, FileH}: true,
	Coord{Rank7, FileH}: true,
	Coord{Rank8, FileH}: true,
}
